// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Hooks","status":true,"description":"","parameters":{}},
{"name":"Override","status":true,"description":"","parameters":{}},
{"name":"ScriptCommands","status":true,"description":"","parameters":{}},
{"name":"FolderPluginLoader","status":true,"description":"加载文件夹内的插件,入口文件main.js.","parameters":{"plugin1":"Basketball","plugin2":"Sgmud","plugin3":"","plugin4":"","plugin5":"","plugin6":"","plugin7":"","plugin8":"","plugin9":"","plugin10":"","plugin11":"","plugin12":"","plugin13":"","plugin14":"","plugin15":"","plugin16":"","plugin17":"","plugin18":"","plugin19":"","plugin20":"","plugin21":"","plugin22":"","plugin23":"","plugin24":"","plugin25":"","plugin26":"","plugin27":"","plugin28":"","plugin29":"","plugin30":"","plugin31":"","plugin32":"","plugin33":"","plugin34":"","plugin35":""}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CharacterEnemy","status":true,"description":"","parameters":{}},
{"name":"test","status":true,"description":"","parameters":{}},
{"name":"TextBalloon","status":true,"description":"让NPC显示对话气球.使用方法：在事件编辑器中输入this.setupTextBalloon('你好呀~~！')","parameters":{}},
{"name":"ProgressBar","status":true,"description":"","parameters":{}}
];
